"""
FastAPI application entry point (Deliverable B). Run with:

    uvicorn api.app:app --host 0.0.0.0 --port 8000

from the management/ directory, with requirements.txt installed in the
service's venv (fastapi/uvicorn/pydantic/jinja2/pyyaml/ovsdbapp) and
python3-libvirt/python3-rados/python3-rbd available on PATH for the
system Python those bindings need (see requirements.txt's header note on
why those three are dnf, not pip, packages).

Interactive API documentation (per operator request) is auto-generated by
FastAPI at /docs (Swagger UI) and /redoc once this app is running --
every route's docstring in api/routes.py, and every field description in
api/models.py, appears there automatically. See README.md's "API and
versioning" section for a plain-text summary of the same endpoints for
offline/airgapped review without a running server.
"""
from __future__ import annotations

from contextlib import asynccontextmanager

from fastapi import FastAPI, Request

from api.routes import API_VERSION, router
from core.logging_setup import log
from core.state import store
from services.cluster_config import load_deployment_config
from services.missions import load_host_inventory
from services.reconciliation import reconcile_on_startup


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Runs once, before this service starts accepting any requests: scans
    every host's actual live libvirt domains and reconciles them against
    the mission database (already reloaded from persistent storage at
    import time, if MISSION_DB_PATH is set -- see core/state.py's module
    docstring), so restart-induced drift (a mission the database has no
    record of, or one missing VMs it should have) is surfaced immediately
    rather than silently. See services/reconciliation.py for exactly what
    this can and can't recover. Never prevents startup -- a reconciliation
    failure (e.g. a host unreachable) is logged and the service starts
    anyway, since serving new requests is more valuable than blocking on
    a best-effort consistency check.
    """
    try:
        hosts = load_host_inventory()
        deployment_cfg = load_deployment_config()
        report = reconcile_on_startup(hosts, store, ssh_user=deployment_cfg.management_ssh_user)
        log.info("startup: reconciliation complete: %s", report.as_dict())
    except Exception as exc:  # noqa: BLE001 - startup must proceed regardless
        log.error("startup: reconciliation failed, starting anyway: %s", exc, exc_info=True)
    yield


app = FastAPI(
    title="Mission Compute Cluster Management API",
    description=(
        "Deliverable B: provisions VMware-replacement 'missions' (VM sets "
        "with NICs, storage, and placement) on a RHEL/KVM/libvirt/OVS-OVN/"
        "Ceph cluster."
    ),
    version=API_VERSION,
    lifespan=lifespan,
)

app.include_router(router)


@app.middleware("http")
async def add_api_version_header(request: Request, call_next):
    """Attach X-API-Version to every response, so a client can always tell which API contract it's talking to."""
    response = await call_next(request)
    response.headers["X-API-Version"] = API_VERSION
    return response


@app.get("/")
async def root():
    """Service identity + pointer to the interactive API docs."""
    return {"service": "mission-compute-cluster-management", "api_version": API_VERSION, "docs": "/docs"}
