"""
FastAPI application entry point (Deliverable B). Run with:

    uvicorn api.app:app --host 0.0.0.0 --port 8000

from the management/ directory, with requirements.txt installed in the
service's venv (fastapi/uvicorn/pydantic/jinja2/pyyaml/ovsdbapp) and
python3-libvirt/python3-rados/python3-rbd available on PATH for the
system Python those bindings need (see requirements.txt's header note on
why those three are dnf, not pip, packages).

Interactive API documentation (per operator request) is auto-generated by
FastAPI at /docs (Swagger UI) and /redoc once this app is running --
every route's docstring in api/routes.py, and every field description in
api/models.py, appears there automatically. See README.md's "API and
versioning" section for a plain-text summary of the same endpoints for
offline/airgapped review without a running server.
"""
from __future__ import annotations

from fastapi import FastAPI, Request

from api.routes import API_VERSION, router

app = FastAPI(
    title="Mission Compute Cluster Management API",
    description=(
        "Deliverable B: provisions VMware-replacement 'missions' (VM sets "
        "with NICs, storage, and placement) on a RHEL/KVM/libvirt/OVS-OVN/"
        "Ceph cluster."
    ),
    version=API_VERSION,
)

app.include_router(router)


@app.middleware("http")
async def add_api_version_header(request: Request, call_next):
    """Attach X-API-Version to every response, so a client can always tell which API contract it's talking to."""
    response = await call_next(request)
    response.headers["X-API-Version"] = API_VERSION
    return response


@app.get("/")
async def root():
    """Service identity + pointer to the interactive API docs."""
    return {"service": "mission-compute-cluster-management", "api_version": API_VERSION, "docs": "/docs"}
