"""
Placement validation: given a mission's static placement (VM -> host) and
the cluster's host inventory, confirm no host is oversubscribed on CPU,
memory, or GPU count, per the design doc:

    total_cpu = sum(vm.cpu for vm in mission.vms.values() if placement[vm_name]==host)
    assert total_cpu <= host_inventory[host]['cpus']

Placement itself is static (operator- or generator-supplied) for this
prototype -- the design doc explicitly scopes auto-scheduling as future
work ("placement: map of VM name -> host... In future, this could be
auto-generated by a scheduler"). `greedy_place` below is a simple
reference bin-packer used only by tools/generate_mission.py to produce a
starting placement file; the runtime path always validates whatever
placement was supplied, regardless of how it was derived.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from .types import HostSpec, MissionSpec


@dataclass
class PlacementViolation:
    host: str
    resource: str      # "cpu" | "memory_mb" | "gpus"
    requested: int
    available: int


@dataclass
class PlacementReport:
    violations: list[PlacementViolation] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.violations

    def as_dict(self) -> dict:
        return {
            "ok": self.ok,
            "violations": [
                {
                    "host": v.host,
                    "resource": v.resource,
                    "requested": v.requested,
                    "available": v.available,
                }
                for v in self.violations
            ],
        }


def validate_placement(mission: MissionSpec, hosts: dict[str, HostSpec]) -> PlacementReport:
    report = PlacementReport()

    unknown_hosts = set(mission.placement.values()) - set(hosts.keys())
    if unknown_hosts:
        for host in sorted(unknown_hosts):
            report.violations.append(PlacementViolation(host, "unknown_host", 0, 0))
        return report  # can't compute per-host totals against hosts we don't know

    per_host_cpu: dict[str, int] = {h: 0 for h in hosts}
    per_host_mem: dict[str, int] = {h: 0 for h in hosts}
    per_host_gpu: dict[str, int] = {h: 0 for h in hosts}

    for vm_name, vm in mission.vms.items():
        host = mission.placement[vm_name]
        per_host_cpu[host] += vm.cpu
        per_host_mem[host] += vm.memory_mb
        if vm.gpu:
            per_host_gpu[host] += 1

    for host_name, host in hosts.items():
        if per_host_cpu[host_name] > host.cpus:
            report.violations.append(
                PlacementViolation(host_name, "cpu", per_host_cpu[host_name], host.cpus)
            )
        if per_host_mem[host_name] > host.memory_mb:
            report.violations.append(
                PlacementViolation(host_name, "memory_mb", per_host_mem[host_name], host.memory_mb)
            )
        if per_host_gpu[host_name] > host.gpus:
            report.violations.append(
                PlacementViolation(host_name, "gpus", per_host_gpu[host_name], host.gpus)
            )

    return report


def greedy_place(vm_names_in_order: list[str], vm_requirements: dict[str, dict], hosts: dict[str, HostSpec]) -> dict[str, str]:
    """
    Simple reference bin-packer: place VMs onto the least-loaded feasible
    host, GPU VMs restricted to hosts with spare GPU slots. Used only to
    generate a first-draft placement file (tools/generate_mission.py) --
    NOT invoked at deployment time. A smarter scheduler is explicitly
    future work per the design doc.
    """
    remaining_cpu = {h: host.cpus for h, host in hosts.items()}
    remaining_mem = {h: host.memory_mb for h, host in hosts.items()}
    remaining_gpu = {h: host.gpus for h, host in hosts.items()}

    placement: dict[str, str] = {}
    for vm_name in vm_names_in_order:
        req = vm_requirements[vm_name]
        candidates = [
            h for h in hosts
            if remaining_cpu[h] >= req["cpu"]
            and remaining_mem[h] >= req["memory_mb"]
            and remaining_gpu[h] >= (1 if req.get("gpu") else 0)
        ]
        if not candidates:
            raise RuntimeError(f"no feasible host for VM '{vm_name}' (requirements: {req})")
        # Prefer the host with the most spare CPU headroom (simple greedy
        # load-spreading heuristic).
        chosen = max(candidates, key=lambda h: remaining_cpu[h])
        placement[vm_name] = chosen
        remaining_cpu[chosen] -= req["cpu"]
        remaining_mem[chosen] -= req["memory_mb"]
        if req.get("gpu"):
            remaining_gpu[chosen] -= 1

    return placement
